### ISSUE TITLE
[Solved] Mastodon OAuth access token could not be obtained: Error getting OAuth access token

### ISSUE THREAD

**Issue by ernolf** [nextcloud/integration_mastodon#48]
App-Version 2.0.2, newly installed
Nextcloud 26.0.1

Settings:
1. Admin
![image](https://github.com/nextcloud/integration_mastodon/assets/39901936/2eeb07fd-0296-4687-9c4d-38d110a0cc03)

2. Personal
![image](https://github.com/nextcloud/integration_mastodon/assets/39901936/96784f14-7f85-4f88-bcdd-cf7baa3dbe39)

With or without "*Use a popup to authenticate*", with or without "*Enable navigation links*"; the confirmation window/popup comes with my profile but fails after all, throwing this error:

Toast-Error-Message:
```
Mastodon OAuth access token could not be obtained: Error getting OAuth access token Client error: `POST https://ernolf@mastodon.social/oauth/token` resulted in a `401 Unauthorized` response:
{"error":"invalid_client","error_description":"Client authentication failed due to unknown client, no client authenticat (truncated...)
```

nextcloud.log:
```
{
  "reqId": "aM5OdOSHCkuFhXDvNcNp",
  "level": 2,
  "time": "2023-05-12T12:22:33+00:00",
  "remoteAddr": "192.168.188.215",
  "user": "ich",
  "app": "integration_mastodon",
  "method": "GET",
  "url": "/apps/integration_mastodon/oauth-redirect?code=qyQKIlUfwa5sqggkYgthGC6XnlNaVy4qB01nwWQPPlM",
  "message": "Mastodon OAuth error : GuzzleHttp\\Exception\\ClientException: Client error: `POST https://ernolf@mastodon.social/oauth/token` resulted in a `401 Unauthorized` response:\n{\"error\":\"invalid_client\",\"error_description\":\"Client authentication failed due to unknown client, no client authenticat (truncated...)\n in /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php:113\nStack trace:\n#0 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\\Exception\\RequestException::create()\n#1 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()\n#2 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\\Promise\\Promise::callHandler()\n#3 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()\n#4 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\\Promise\\TaskQueue->run()\n#5 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\\Promise\\Promise->invokeWaitFn()\n#6 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#7 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()\n#8 /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#9 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\\Promise\\Promise->wait()\n#10 /var/www/nextcloud/lib/private/Http/Client/Client.php(297): GuzzleHttp\\Client->request()\n#11 /var/www/nextcloud/apps/integration_mastodon/lib/Service/MastodonAPIService.php(351): OC\\Http\\Client\\Client->post()\n#12 /var/www/nextcloud/apps/integration_mastodon/lib/Controller/ConfigController.php(117): OCA\\Mastodon\\Service\\MastodonAPIService->requestOAuthAccessToken()\n#13 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\\Mastodon\\Controller\\ConfigController->oauthRedirect()\n#14 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\\AppFramework\\Http\\Dispatcher->executeController()\n#15 /var/www/nextcloud/lib/private/AppFramework/App.php(183): OC\\AppFramework\\Http\\Dispatcher->dispatch()\n#16 /var/www/nextcloud/lib/private/Route/Router.php(315): OC\\AppFramework\\App::main()\n#17 /var/www/nextcloud/lib/base.php(1056): OC\\Route\\Router->match()\n#18 /var/www/nextcloud/index.php(36): OC::handleRequest()\n#19 {main}",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
  "version": "26.0.1.1",
  "data": {
    "app": "integration_mastodon"
  }
}
{
  "reqId": "aM5OdOSHCkuFhXDvNcNp",
  "level": 2,
  "time": "2023-05-12T12:22:33+00:00",
  "remoteAddr": "192.168.188.215",
  "user": "ich",
  "app": "integration_mastodon",
  "method": "GET",
  "url": "/apps/integration_mastodon/oauth-redirect?code=qyQKIlUfwa5sqggkYgthGC6XnlNaVy4qB01nwWQPPlM",
  "message": "Mastodon OAuth get token error : code=qyQKIlUfwa5sqggkYgthGC6XnlNaVy4qB01nwWQPPlM ; url=https://ernolf@mastodon.social ; clientId=-CRxII55cdpMMBKvts7UONlVeoC6BrAyKCY13v7JiiU ; clientSecret=X0fuUC9tAcuJsscP9nK_-CpywkllBnLIWXq83HJ78Js ; redirect_uri=https://global-social.net/apps/integration_mastodon/oauth-redirect",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
  "version": "26.0.1.1",
  "data": {
    "app": "integration_mastodon"
  }
}
```

What did I do wrong?

**Comment by andrey18106** [comment]
@ernolf Hi! You should use https://mastodon.social as Mastodon instance address in personal settings.

**Comment by ernolf** [comment]
> @ernolf Hi! You should use https://mastodon.social as Mastodon instance address in personal settings.

Thank you so much @andrey18106 
This was not apparent to me at all, since I got a clean login page. This could possibly be better documented.
But at least anyone who makes the same mistake now will find the solution here 😉
